[2021-11-10 15:50:41,372] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2021-11-10T14:50:25.031474+00:00 [queued]>
[2021-11-10 15:50:41,381] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: example_bash_operator.also_run_this manual__2021-11-10T14:50:25.031474+00:00 [queued]>
[2021-11-10 15:50:41,382] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-10 15:50:41,382] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-10 15:50:41,382] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-10 15:50:41,388] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): also_run_this> on 2021-11-10 14:50:25.031474+00:00
[2021-11-10 15:50:41,391] {standard_task_runner.py:52} INFO - Started process 249757 to run task
[2021-11-10 15:50:41,393] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_bash_operator', 'also_run_this', 'manual__2021-11-10T14:50:25.031474+00:00', '--job-id', '19', '--raw', '--subdir', '/home/dnieto/.pyenv/versions/3.8.11/envs/***/lib/python3.8/site-packages/***/example_dags/example_bash_operator.py', '--cfg-path', '/tmp/tmpmvm1w8c_', '--error-file', '/tmp/tmpok6nv9by']
[2021-11-10 15:50:41,393] {standard_task_runner.py:77} INFO - Job 19: Subtask also_run_this
[2021-11-10 15:50:41,414] {logging_mixin.py:109} INFO - Running <TaskInstance: example_bash_operator.also_run_this manual__2021-11-10T14:50:25.031474+00:00 [running]> on host workstation
[2021-11-10 15:50:41,444] {taskinstance.py:1427} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_bash_operator
AIRFLOW_CTX_TASK_ID=also_run_this
AIRFLOW_CTX_EXECUTION_DATE=2021-11-10T14:50:25.031474+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-10T14:50:25.031474+00:00
[2021-11-10 15:50:41,445] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-10 15:50:41,445] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'echo "run_id=manual__2021-11-10T14:50:25.031474+00:00 | dag_run=<DagRun example_bash_operator @ 2021-11-10 14:50:25.031474+00:00: manual__2021-11-10T14:50:25.031474+00:00, externally triggered: True>"']
[2021-11-10 15:50:41,448] {subprocess.py:85} INFO - Output:
[2021-11-10 15:50:41,448] {subprocess.py:89} INFO - run_id=manual__2021-11-10T14:50:25.031474+00:00 | dag_run=<DagRun example_bash_operator @ 2021-11-10 14:50:25.031474+00:00: manual__2021-11-10T14:50:25.031474+00:00, externally triggered: True>
[2021-11-10 15:50:41,448] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-10 15:50:41,462] {taskinstance.py:1270} INFO - Marking task as SUCCESS. dag_id=example_bash_operator, task_id=also_run_this, execution_date=20211110T145025, start_date=20211110T145041, end_date=20211110T145041
[2021-11-10 15:50:41,485] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-10 15:50:41,505] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
